### ISSUE TITLE
DMCA process automation

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots-admin#2]
Investigate and automate steps needed to handle DMCA violating content

**Comment by 6a68** [comment]
consider https://github.com/gene1wood/birch-girder/ if github is the place to store / manage those requests

**Comment by 6a68** [comment]
The Screenshots DMCA link goes to Mozilla's DMCA page: https://www.mozilla.org/en-US/about/legal/report-infringement/

@clouserw Any idea how a DMCA request would flow from the main legal bucket to us? Is it someone manually forwarding an email?

**Comment by ianb** [comment]
I think we're still good manually handling these requests, we just want them to be more automated than opening a Bugzilla ticket with some SQL to be run. So we want a form field where we can paste a URL (image URL, shot URL, shot ID) and have it run the necessary SQL.

**Comment by ianb** [comment]
Given the discussion, I believe this is done via #18
