### ISSUE TITLE
Define illegal/quarantine takedown

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots-admin#30]
We allude to this in several places, but we haven't specified how we would implement it, or if we're going to implement it at this moment.

**Comment by clouserw** [comment]
As of now:

- Screenshots pings Watchdog with an image
- Watchdog returns a positive flag
- Screenshots flags that image (which removes it from public view)
- The legal team is notified and will review the image to see if it's a false positive or not
- The legal team will communicate with me about removing or restoring the image (via the screenshots-admin tool)

It's a super manual process, but until we have a sense of how much we need to scale, that will work for now.
