### ISSUE TITLE
Set up CI to build and deploy docker images

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots-admin#36]
We can follow the approach used by Screenshots:

- CI builds and uploads the docker images
- CI holds the docker hub creds, inserted by ops

**Comment by autrilla** [comment]
I'm going to need admin permissions on this repo in order to set up CI

**Comment by oremj** [comment]
@autrilla I gave you admin.

**Comment by autrilla** [comment]
https://circleci.com/gh/mozilla-services/screenshots-admin/3 images are now getting pushed
