### ISSUE TITLE
Some more requirements

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots-admin#6]
I pulled this list out of some old legal notes I stumbled across.  These aren't necessarily required for launch and some are even a little vague.  I suggest we split this out into separate issues.

- Should be able to delete a shot based on the image URL
- Should be able to delete a shot based on the share page URL
- Should be able to quarantine a shot based on either of the above
- Should be able to get information about the user or upload
  - In particular repeat offender policy information
  - DeviceID
- Avoid IP address
- Any log information that’s still available
- Should be able to permaban a user
- NCMEC/MSFT integration
- NCMEC’s CVIP: http://www.missingkids.com/CVIP

**Comment by ianb** [comment]
> Should be able to quarantine a shot based on either of the above

This needs some more definition. *Maybe* this means: take all the shot information, encrypt it and upload it to a separate S3 bucket, then delete it from the production server.

> Any log information that’s still available

I'd like to see if we can simply construct an appropriate link to the logging app(s) we're using. I don't want to try to implement a log browser in this app.

> Should be able to permaban a user

Strike user, replace with deviceId. But, we need some spec on this. Just disable the account? We can do that by wiping their password. If we want to tell the deviceId that it is blocked, then there's more UI that has to go in the Screenshots app.

> NCMEC/MSFT integration

Is this something that needs ops to intervene? I got the impression that PhotoDNA can act in a pretty hands-off way, and if so then all the logic would go in Screenshots or a separate service. The admin app is strictly for cases where a person needs to intervene.

**Comment by wresuolc** [comment]
>     Should be able to quarantine a shot based on either of the above
> 
> This needs some more definition. Maybe this means: take all the shot information, encrypt it and upload it to a separate S3 bucket, then delete it from the production server.
> 
It could.  When I wrote it I mostly wanted to make sure we could set a flag that would prevent authors or random people from loading the image (or deleting or editing).

>     Any log information that’s still available
> 
> I'd like to see if we can simply construct an appropriate link to the logging app(s) we're using. I don't want to try to implement a log browser in this app.

:+1: 

>     Should be able to permaban a user
> 
> Strike user, replace with deviceId. But, we need some spec on this. Just disable the account? We can do that by wiping their password. If we want to tell the deviceId that it is blocked, then there's more UI that has to go in the Screenshots app.

I wasn't expecting a UI change here, but really, we haven't come across a case where we would need this yet.  Maybe we can skip this for now.

> 
>     NCMEC/MSFT integration
> 
> Is this something that needs ops to intervene? I got the impression that PhotoDNA can act in a pretty hands-off way, and if so then all the logic would go in Screenshots or a separate service. The admin app is strictly for cases where a person needs to intervene.

I'm working with legal on what this interface should look like.  Stay tuned!

**Comment by ianb** [comment]
We should revisit this given #18 (which follows the design in #7)

**Comment by ianb** [comment]
Everything here is either in another ticket, or we're okay not doing it now.
