### ISSUE TITLE
Deployment (Dockerization)

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots-admin#8]
@oremj, some ops questions:

- How should we package this app for release? Should we Dockerize this one-page Node + React app?
- Can we have a dev environment that is accessible to the (LDAP-authed) devs, that can be tested against the dev Screenshots server?

**Comment by 6a68** [comment]
I can be on the hook to do the Docker work, since Ian's doing the initial build tools work

**Comment by 6a68** [comment]
@oremj Any thoughts here?

**Comment by oremj** [comment]
Yes, this should be dockerized.

Will the production environment also be LDAP-authed? If LDAP auth is what we want for this app, I can work with IT on setting this up behind an auth0 portal.

**Comment by 6a68** [comment]
@oremj The production environment will be behind whatever ops typically uses to protect admin interfaces. I'm guessing it'd be accessible behind a jump host, maybe?

**Comment by 6a68** [comment]
Aha! from jvehent, quoted in #3:

> "We put admin panels behind VPN and auth0 authentication. Normandy, Kinto and Balrog have good examples of how to achieve this."

@oremj yeah, I think setting up auth0 would be good. I'll get the Docker build sorted this week.
